server:
  # service startup port
  port: 18001

redis:
  uri: localhost:16379
  user:
  password:
  db: 0

nats:
  uri:

network:
  - id: 314159
    name: FileCoin-Calibration
    idPrefix: t0
    queryRpc:
      - https://calibration.filfox.info/rpc/v1
    contractRpc: https://calibration.filfox.info/rpc/v1
    oracleContract: 0x1B9e5E36635e73426Dc0DD3E3ec4070A86099B82
    oracleStartHeight: 1740975
    oracleAbi: oracle.json

github:
  # github token
  token:
    - 
    # graphql api
  graphql: https://api.github.com/graphql