server:
  # service startup port
  port: :8888
  
  # subgraph api
subgraph:
  url: "http://localhost:"

# drand api
drand: 
  url: "https://api.drand.secureweb3.com:6875"
  chainHash: "52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971"

ipfs:
  token:
  uploadPath: "https://api.nft.storage/upload"

network:
#    - id: 1
#      name: fileCoin-main
#      # RPC url
#      rpc: https://rpc.ankr.com/filecoin
#      #  absolute path
#      abiPath: /dist/power-voting.abi
#      # subgraph url
#      subgraphUrl: "http://localhost:"
#      # contract address
#      contractAddress:
#      # wallet private key
#      privateKey:
#      # wallet address
#      walletAddress:
#      # gas limit
#      gasLimit: 200000000
#    - id: 314159
#      name: fileCoin-test
#      rpc: https://api.calibration.node.glif.io/rpc/v1
#      abiPath: /dist/power-voting.abi
#      subgraphUrl: http://192.168.11.94:8000/subgraphs/name/powervoting
#      contractAddress:
#      privateKey:
#      walletAddress:
#      gasLimit: 200000000
    - id: 11155111
      name: sepolia
      rpc: https://ethereum-sepolia.blockpi.network/v1/rpc/public	
      abiPath: /Users/lijianrong/workspace/PV/powervoting/contracts/powervoting/PowerVoting.json
      subgraphUrl: http://192.168.11.94:8000/subgraphs/name/powervoting
      contractAddress: 0x23E33253ca50B7E59EDc6d1377208dcD4F54C019
      privateKey: 
      walletAddress: 
      gasLimit: 3000000
