name: powervoting-contracts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'powervoting-contracts/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'powervoting-contracts/*'
env:
  FOUNDRY_PROFILE: ci


