name: Trigger Jenkins Frontend Build
on:
  push:
    branches:
      - main
    paths:
      - frontend/*
jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        run: |
          curl -X POST http://162.219.87.220:4972/job/pv-frontend-pro/build?token=pv-frontend-pro